#
# _config.yml for AWS Icons
#

exclude: [ "CNAME", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://animal-identicons.svg.zone
title: Animal Identicons
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
links:
  - name: Download originals
    url: "https://github.com/camelmasa/animal-identicon-js/blob/master/src/animal-identicon.js"
  - name: Report an issue
    url: "https://github.com/AwesomeLogos/animal-identicons/issues"
